FaqCategory.create(name: "Settling In")
FaqCategory.create(name: "Home Care")
FaqCategory.create(name: "Troubleshooting")
FaqCategory.create(name: "Urgent")
FaqCategory.create(name: "General")
FaqCategory.create(name: "Reservation")
FaqCategory.create(name: "Purchasing Process")
FaqCategory.create(name: "Health and Safety")
FaqCategory.create(name: "Building Maintenance")
FaqCategory.create(name: "Management")