global = Global.create(name: "CFAdmin")
build_sequence = BuildSequence.create(build_sequenceable: global)
BuildStep.create(build_sequence_id: build_sequence.id, order: 1, title: "Building Soon", description: "Your build progress has been updated to:\r\n\r\nBuilding Soon")
BuildStep.create(build_sequence_id: build_sequence.id, order: 2, title: "Roof On", description: "Your build progress has been updated to:\r\n\r\nRoof On")
BuildStep.create(build_sequence_id: build_sequence.id, order: 3, title: "In Progress", description: "Your build progress has been updated to:\r\n\r\nIn Progress")
BuildStep.create(build_sequence_id: build_sequence.id, order: 4, title: "First Fix", description: "Your build progress has been updated to:\r\n\r\nFirst Fix")
BuildStep.create(build_sequence_id: build_sequence.id, order: 5, title: "Second Fix", description: "Your build progress has been updated to:\r\n\r\nSecond Fix")
BuildStep.create(build_sequence_id: build_sequence.id, order: 6, title: "Kitchen Installed", description: "Your build progress has been updated to:\r\n\r\nKitchen Installed")
BuildStep.create(build_sequence_id: build_sequence.id, order: 7, title: "Sanitaryware Installed", description: "Your build progress has been updated to:\r\n\r\nSanitaryware Installed")
BuildStep.create(build_sequence_id: build_sequence.id, order: 8, title: "Decoration Completed", description: "Your build progress has been updated to:\r\n\r\nDecoration Completed")
BuildStep.create(build_sequence_id: build_sequence.id, order: 9, title: "Tiling Completed", description: "Your build progress has been updated to:\r\n\r\nTiling Completed")
BuildStep.create(build_sequence_id: build_sequence.id, order: 10, title: "Flooring Completed", description: "Your build progress has been updated to:\r\n\r\nFlooring Completed")
BuildStep.create(build_sequence_id: build_sequence.id, order: 11, title: "Patio/driveway Completed", description: "Your build progress has been updated to:\r\n\r\nPatio/driveway Completed")
BuildStep.create(build_sequence_id: build_sequence.id, order: 12, title: "Landscaping Completed", description: "Your build progress has been updated to:\r\n\r\nLandscaping Completed")
BuildStep.create(build_sequence_id: build_sequence.id, order: 13, title: "Ready for Exchange", description: "Your build progress has been updated to:\r\n\r\nReady for Exchange")
BuildStep.create(build_sequence_id: build_sequence.id, order: 14, title: "Ready to Complete", description: "Your build progress has been updated to:\r\n\r\nReady to Complete")
BuildStep.create(build_sequence_id: build_sequence.id, order: 15, title: "Building Complete", description: "Your build progress has been updated to:\r\n\r\nBuilding Complete")
EnvVar.create(name: "services", value: "https://skyinyourhome.sky.com/spaciable")
EnvVar.create(name: "living_sign_in", value: "https://spaciableliving.com/version-staging2/sign_in")
EnvVar.create(name: "firebase_url", value: "https://firebasedynamiclinks.googleapis.com/v1/")
EnvVar.create(name: "firebase_api_key", value: "AIzaSyAwr2okWOtcJYoHfL9FO0wqcEc1bpZ19pg")
EnvVar.create(name: "living_deep_link", value: "&apn=com.spaciable_living.live&isi=1564735567&ibi=com.bubbleapps.livingapp")
EnvVar.create(name: "firebase_living_domain", value: "https://spaciableliving.page.link")
EnvVar.create(name: "firebase_shorten_endpoint", value: "shortLinks")
EnvVar.create(name: "create_living_resident", value: "https://spaciableliving.com/version-staging2/create-resident?invitation_token=INVITATION_TOKEN")
EnvVar.create(name: "living_password_reset", value: "https://spaciableliving.com/version-staging2/create-resident?reset_password_token=RESET_PASSWORD_TOKEN")
EnvVar.create(name: "savings_spotlight", value: "Sky Spotlight Tile.png")
EnvVar.create(name: "unlatch_email", value: "apitest@spaciable.com")
EnvVar.create(name: "unlatch_password", value: "1uiHs5x68")
EnvVar.create(name: "unlatch_token", value: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjc1MzExNTU3NSwiZXhwIjoxNjkwMjk0MDkxfQ.I4CmilnqQHoahxZl_ZMSdnqN4-fl1gugVS9dnDBNH2k")
EnvVar.create(name: "unlatch_url", value: "https://spaciable-test.getunlatch.com/api/v1/")

