# Alliants Rubocop standards

inherit_from: .rubocop_todo.yml
require: rubocop-rails

AllCops:
  Include:
    - Rakefile
    - Gemfile
    - config.ru
    - app/**/*
  Exclude:
    - app/assets/**/*
    - app/views/**/*
    - config/**/*
    - db/**/*
    - bin/**/*
    - script/**/*
    - vendor/**/*
    - spec/**/*
    - features/**/*
    - lib/tasks/*
    - Guardfile
  TargetRubyVersion: 2.7.1

Rails:
  Enabled: true
Rails/Delegate:
  Enabled: true
  Exclude:
    - lib/**/*

Style/IfUnlessModifier:
  Enabled: true
  Exclude:
    - spec/spec_helper.rb
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true
Naming/MethodName:
  Exclude:
    - features/support/fixtures/create_fixture.rb # ResourceName(resource, parent)
    - app/services/bulk_plots/numbers.rb # Number(int_or_float)
Style/YodaCondition:
  Exclude:
    - app/controllers/documents_controller.rb
Layout/EndOfLine:
  Exclude:
    - app/services/csv/*
Metrics/LineLength:
  Max: 99
  Enabled: true
  Exclude:
    - features/steps/**/*
    - features/support/**/*
    - spec/**/*
Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: true

Style/RedundantReturn:
  AllowMultipleReturnValues: true

# Exclude auto-generated devise controllers
Style/ClassAndModuleChildren:
  Exclude:
    - app/controllers/users/**

# Exclude sessions controllers for after_sign_in_path_for(resource)
# Used to define the dashboard/home path for analytical purposes
Lint/UnusedMethodArgument:
  Exclude:
    - app/controllers/residents/sessions_controller.rb
    - app/controllers/residents/app/sessions_controller.rb
    - app/controllers/users/sessions_controller.rb

Metrics/ClassLength:
  Exclude:
    - "app/models/document.rb"

Metrics/ModuleLength:
  Exclude:
    - "app/helpers/buttons_helper.rb"
