apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: test-and-deploy
"on":
  push:
    branches:
      - "**"
env:
  CI_BRANCH: ${{ cloudbees.scm.branch }}
  CI_BUILD_ID: ${{ cloudbees.run_id }}
  CI_COMMITTER_NAME: ${{ cloudbees.event.head_commit.author.name }}
  CI_COMMITTER_USERNAME: ${{ cloudbees.event.head_commit.author.username }}
  CI_REPO_NAME: ${{ cloudbees.scm.repository}}

permissions:
  scm-token-org: read
  scm-token-own: read

jobs:
  test-cucumber:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Run cucumber
        uses: docker://ruby:2.7.8-bullseye
        run: |-
          ruby -v
        shell: bash
  test-ruby:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Run ruby
        uses: docker://ruby:2.7.8-bullseye
        run: |-
          ruby -v
        shell: bash